### ISSUE TITLE
MOO commands do not seem to work...

### ISSUE THREAD

**Issue by conchis** [toddsundsted/improvise#1]
I was able to build stunt, run improvise, and log in without an error. I did discover that the HTTP server was object #82 (not #83), however other than listing packages I have not been able to get it to recognize any commands. Perhaps there is something I am missing?

Welcome to Stunt!  For information about Stunt, check out http://stunt.io/.  To connect to the server, type "connect <credentials>".
connect F7EA3833B5A14C6DE1CAD27F6172095A52BFFE00C3E13CB3AF08075C31A909D5
**\* Connected ***
; 6 \* 7
42
; #5
#5 "Wizard"

; #5.location
#7 "Home"

"Hello world
I couldn't understand that.
say Hello, where am I?
I couldn't understand that.
eval #0
#0 "System"

@install lambdacore with $composed
Updating index...
Installing version "0.0.5" of package "lambdacore" from the remote archive...
look
Adding package dictionary (The System Object) to parents of $system...
Version "0.0.5" of package "lambdacore" (LambdaCore Package) was successfully installed as #121.
I couldn't understand that.
look
I couldn't understand that.
say Hello
I couldn't understand that.

**Comment by toddsundsted** [comment]
After installing "lambdacore", log out and log back in as "wizard".  Literally:

  connect wizard

This will log you in as the wizard character in lambdacore, rather than as the bootstrap wizard (or programmer) in the Improvise kernel.

At that point you (that player) will have access to all of the usual lambdacore commands.

**Comment by toddsundsted** [comment]
$ telnet localhost 12345
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Welcome to Stunt!  For information about Stunt, check out http://stunt.io/.  To connect to the server, type "connect <credentials>".
connect *\* long hex string **
**\* Connected ***
@install lambdacore with $composed
Updating index...
Installing version "0.0.5" of package "lambdacore" from the remote archive...
Adding package dictionary (The System Object) to parents of $system...
Version "0.0.5" of package "lambdacore" (LambdaCore Package) was successfully installed as #121.
@quit
**\* Disconnected ***
Connection closed by foreign host.
$ telnet localhost 12345
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Welcome to Stunt!  For information about Stunt, check out http://stunt.io/.  To connect to the server, type "connect <credentials>".
connect wizard
**\* Connected ***
The First Room
This is all there is right now.
Hacker is here.
Last connected Thu May 24 00:35:45 2012 EDT from FLUTTERSHY
There is new news.  Type 'news' to read all news or 'news new' to read just new news.
look
The First Room
This is all there is right now.
Hacker is here.
help
Help is available on the following general topics:

...

**Comment by toddsundsted** [comment]
If you go forward with lambdacore on top of improvise, you should disable the bootstrap wizard and programmer, to be more secure.
